repo:
- '*'

# Add 'test' label to any change to *.test.tsx files within the source dir
test:
- frontend-app/src/**/*.test.tsx

# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
source:
- any: ['frontend-app/src/**/*', '!frontend-app/src/docs/*']

# Add 'frontend` label to any change to *.js files as long as the `main.js` hasn't changed
frontend:
- any: ['frontend-app/src/*.tsx', 'frontend-app/src/*.css', 'frontend-app/src/*.ts']

terraform:
- any: ['terraform/*.tf']