name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ development ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # environment name
    environment: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
            
      - name: Install dependencies
        run: yarn
        working-directory: frontend-app

      - name: Build
        run: yarn build
        working-directory: frontend-app

      - name: Test
        run: yarn test
        working-directory: frontend-app
