# This is a basic workflow to help you get started with Actions

name: Deploy to PROD

# Controls when the workflow will run
on:
  release:
    types:
    - published

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # environment name
    environment: prod
    permissions:
      id-token: write
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Download Application Github Release
        run: |
          gh release download ${{ github.event.release.tag_name }} --pattern frontend-app.tar.gz
          tar -xvzf frontend-app.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.GIT_OIDC_PROVIDER_ROLE_ARN }}
          aws-region: us-west-1

      - name: Push files to S3
        run: aws s3 sync build/ s3://${{ secrets.S3_CDN_BUCKET }} --cache-control 5 --exclude ".github/*" 
